### ISSUE TITLE
Sprint 1

### ISSUE THREAD

**Issue by ekilah** [contactpush/contact#16]
/cc @codepathreview @codepath

**Comment by codepathreview** [comment]
:+1: Nice work creating wire-frames and distributing stories/tasks in sprint 1. Great to see the basic screens and flow coming along well. Few notes to mention:
- Well created detailed stories/tasks on the project wiki.
- Group projects can reinforce skills that are relevant to both group and individual work including the ability to plan and manage time. For this reason, it is imperative that you group all issues into milestones representing sprints so that its easier for you to track progress of the project
- Don't forget to assign the tasks equally to all team members
- Good job by everyone to [contribute](https://github.com/contactpush/contact/graphs/contributors) to the project 
- Nice work creating and distributing tasks to create database schema and models.
- Good to see that your team created regular commits to sync up your code to avoid having multiple conflicts at the end.
- Consider creating tasks to QA the app a few times to check the basic flow. Integration testing will especially be important for this project since each team member is working on a separate module. The best part is seeing it all come together into a polished app.

Good to see the basic flow coming along well. Please take notes of these points and improve upon the same in the next sprint. Look forward to the rest of the functionality and improvement on the core flows by the end of the Sprint 2 so you can have enough time to add UI polish and advanced nice-to-have features later on.  It is those little extra things you do that make everything feel more polished and desirable to use.
